### ISSUE TITLE
Import error SDGym

### ISSUE THREAD

**Issue by kat-leen** [sdv-dev/SDGym#145]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDGym version: 0.5.0
* Python version: 3.8.13
* Operating System: macOS 12.4

### Error Description

After installing SDGym, I have encountered two errors during its import:
`RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf`
`ImportError: numpy.core.multiarray failed to import`

### Steps to reproduce

I did the following steps in a terminal to install SDGym (I used pip since the CONDA installation is not working, the package sdgym is not found in the channels):

```
conda create -n sdgym python=3.8
conda activate sdgym
pip install torch
pip install sdgym
```

Then I ran:
```
python
>>> import sdv # works
>>> import sdgym # here comes the crash
Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "XXX/code/SDGym/sdgym/__init__.py", line 15, in <module>
    from sdgym import benchmark, synthesizers
  File "XXX/code/SDGym/sdgym/benchmark.py", line 21, in <module>
    from sdgym.synthesizers.base import Baseline
  File "XXX/code/SDGym/sdgym/synthesizers/__init__.py", line 1, in <module>
    from sdgym.synthesizers.clbn import CLBN
  File "XXX/code/SDGym/sdgym/synthesizers/clbn.py", line 4, in <module>
    from pomegranate import BayesianNetwork, ConditionalProbabilityTable, DiscreteDistribution
  File "YYY/Applications/miniconda3/envs/sdgym/lib/python3.8/site-packages/pomegranate/__init__.py", line 11, in <module>
    from .base import *
  File "pomegranate/base.pyx", line 6, in init pomegranate.base
  File "YYY/Applications/miniconda3/envs/sdgym/lib/python3.8/site-packages/pomegranate/distributions/__init__.py", line 9, in <module>
    from .distributions import *
  File "pomegranate/distributions/distributions.pyx", line 11, in init pomegranate.distributions.distributions
  File "pomegranate/utils.pyx", line 26, in init pomegranate.utils
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import
```

**Comment by npatki** [comment]
Hi @kat-leen, seems like we missed this issue since it was prematurely labeled `under discussion`. Are you still having problems?

The error is probably caused by the separate installation commands, which is resulting in incompatible versions of various libraries (torch, numpy, etc.). 

Is there a reason you are installing torch first, separately from sdgym? The sdgym library automatically includes torch, so I would suggest creating a fresh environment with the following installation: 

```
conda install sdv=0.18.0
conda install sdgym=0.6.0
```

**Comment by npatki** [comment]
I'm closing off this issue since it has been inactive for some time. If you are still having problems, please feel free to reply and we can always reopen the issue to continue the investigation. Thanks.
