### ISSUE TITLE
`expedia_hotel_log` doesn't work

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDGym#216]
No synthesizer can be run on the `expedia_hotel_log` dataset. It crashes with the following error:
```python3
import sdgym
sdgym.benchmark_single_table(synthesizers=['UniformSynthesizer'], sdv_datasets=['expedia_hotel_logs'])
```
```bash
Metric NewRowSynthesis failed on dataset expedia_hotel_logs. Skipping.
Traceback (most recent call last):
  File "pandas/_libs/lib.pyx", line 2369, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "2014-08-11 07:46:59"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mithrilpebble/Desktop/SDGym/sdgym/benchmark.py", line 118, in _compute_scores
    score = metric.compute(*metric_args, **metric_kwargs.get(metric_name, {}))
  File "/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/single_table/new_row_synthesis.py", line 161, in compute
    return cls.compute_breakdown(
  File "/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/single_table/new_row_synthesis.py", line 76, in compute_breakdown
    real_data[field] = pd.to_numeric(real_data[field])
  File "/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/pandas/core/tools/numeric.py", line 185, in to_numeric
    values, _ = lib.maybe_convert_numeric(
  File "pandas/_libs/lib.pyx", line 2411, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "2014-08-11 07:46:59" at position 0
/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/reports/utils.py:661: UserWarning: Unexpected values ("15", "4", "3", "26", "16" + more) in column "site_name"
  warnings.warn(warning_format.format(values=values, column=column))
/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/reports/utils.py:661: UserWarning: Unexpected values ("183", "71", "26", "181", "146" + more) in column "user_location_country"
  warnings.warn(warning_format.format(values=values, column=column))
/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/reports/utils.py:661: UserWarning: Unexpected values ("622", "506", "54", "743", "480" + more) in column "user_location_region"
  warnings.warn(warning_format.format(values=values, column=column))
/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/reports/utils.py:661: UserWarning: Unexpected values ("55115", "31629", "33653", "45435", "15378" + more) in column "user_location_city"
  warnings.warn(warning_format.format(values=values, column=column))
/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/reports/utils.py:661: UserWarning: Unexpected values ("4702", "2361", "5114", "5256", "2436" + more) in column "user_id"
  warnings.warn(warning_format.format(values=values, column=column))
/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/reports/utils.py:661: UserWarning: Unexpected values ("8", "6") in column "channel"
  warnings.warn(warning_format.format(values=values, column=column))
/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/reports/utils.py:661: UserWarning: Unexpected values ("20762", "43673", "57929", "17182", "44873" + more) in column "srch_destination_id"
  warnings.warn(warning_format.format(values=values, column=column))
/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/reports/utils.py:661: UserWarning: Unexpected values ("2") in column "srch_destination_type_id"
  warnings.warn(warning_format.format(values=values, column=column))
/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/reports/utils.py:661: UserWarning: Unexpected values ("152", "154", "73", "53", "202" + more) in column "hotel_country"
  warnings.warn(warning_format.format(values=values, column=column))
/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/reports/utils.py:661: UserWarning: Unexpected values ("1693", "1869", "845", "673", "698" + more) in column "hotel_market"
  warnings.warn(warning_format.format(values=values, column=column))
/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/reports/utils.py:661: UserWarning: Unexpected values ("31", "87", "27", "23", "74") in column "hotel_cluster"
  warnings.warn(warning_format.format(values=values, column=column))
Error running UniformSynthesizer on dataset expedia_hotel_logs;
Traceback (most recent call last):
  File "/Users/mithrilpebble/Desktop/SDGym/sdgym/benchmark.py", line 175, in _score
    _compute_scores(
  File "/Users/mithrilpebble/Desktop/SDGym/sdgym/benchmark.py", line 140, in _compute_scores
    quality_report.generate(real_data, synthetic_data, metadata, verbose=False)
  File "/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/reports/single_table/quality_report.py", line 77, in generate
    self._metric_results[metric.__name__] = metric.compute_breakdown(
  File "/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/single_table/multi_column_pairs.py", line 129, in compute_breakdown
    breakdown[sorted_columns] = cls.column_pairs_metric.compute_breakdown(
  File "/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/sdmetrics/column_pairs/statistical/correlation_similarity.py", line 103, in compute_breakdown
    correlation_real, _ = correlation_fn(real_data[column1], real_data[column2])
  File "/Users/mithrilpebble/opt/anaconda3/envs/test/lib/python3.9/site-packages/scipy/stats/_stats_py.py", line 4432, in pearsonr
    dtype = type(1.0 + x[0] + y[0])
TypeError: unsupported operand type(s) for +: 'float' and 'str'
```

**Comment by npatki** [comment]
Ultimately, we should make sure that the benchmarking script is fault-tolerant. If an individual piece of code doesn't run, it should catch the error and report a `NaN` in the final results. [See docs](https://docs.sdv.dev/sdgym/benchmarking/interpreting-results#errors) for desired behavior.

Note that there are several related issues to this dataset & metric combo (not direct causes):

- [SDV 1375](https://github.com/sdv-dev/SDV/issues/1375): The metadata for `expedia_hotel_logs` doesn't accurately reflect the data
- [SDMetrics 337](https://github.com/sdv-dev/SDMetrics/issues/337): The metric is trying to convert this into a number instead of a datetime

**Comment by fealho** [comment]
As mentioned in #219, SDGym benchmarking is already fault-tolerant, so no changes need to be made in SDGym.
