### ISSUE TITLE
Error benchmarking Tablegan on the Intrusion Dataset

### ISSUE THREAD

**Issue by csala** [sdv-dev/SDGym#36]
An error shows up Tablegan is benchmarked on the `intrusion` dataset.

This is the shown traceback.

```
2020-05-11 22:09:26,240 - INFO - base - Sampling TableganSynthesizer
2020-05-11 22:09:28,757 - ERROR - benchmark - Error computing scores for TableganSynthesizer on dataset intrusion - iteration 0
Traceback (most recent call last):
  File "/home/xals/Projects/SDGym/sdgym/benchmark.py", line 71, in compute_benchmark
    scores = compute_scores(train, test, synthesized, meta)
  File "/home/xals/Projects/SDGym/sdgym/evaluate.py", line 358, in compute_scores
    scores = evaluator(synthesized_data, test, metadata)
  File "/home/xals/Projects/SDGym/sdgym/evaluate.py", line 162, in _evaluate_multi_classification
    x_train, y_train, x_test, y_test, classifiers = _prepare_ml_problem(train, test, metadata)
  File "/home/xals/Projects/SDGym/sdgym/evaluate.py", line 143, in _prepare_ml_problem
    x_train, y_train = fm.make_features(train)
  File "/home/xals/Projects/SDGym/sdgym/evaluate.py", line 132, in make_features
    feature = encoder.fit_transform(col)
  File "/home/xals/.virtualenvs/SDGym/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py", line 631, in fit_transform
    return self.fit(X).transform(X)
  File "/home/xals/.virtualenvs/SDGym/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py", line 493, in fit
    self._fit(X, handle_unknown=self.handle_unknown)
  File "/home/xals/.virtualenvs/SDGym/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py", line 80, in _fit
    X_list, n_samples, n_features = self._check_X(X)
  File "/home/xals/.virtualenvs/SDGym/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py", line 49, in _check_X
    X_temp = check_array(X, dtype=None)
  File "/home/xals/.virtualenvs/SDGym/lib/python3.6/site-packages/sklearn/utils/validation.py", line 542, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/home/xals/.virtualenvs/SDGym/lib/python3.6/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

**Comment by csala** [comment]
NOTE: Error happens only when running with a high number of epochs such as the default 300. Using a lower number of epochs like 1 or 10 there is no crash and scores are produced as expected.

**Comment by csala** [comment]
This is not happening anymore after the latest updates.
